excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://crizgonzalez.io
title: criz
tagline: tech + social science
description: 'I did't say it, but if I did I was drunk' 
paginate: 3
